language: node_js
node_js:
  "8.12.0"
before_install:
  npm install grunt-cli -g
install:
  npm install  
script: 
  - grunt
deploy:
  provider: pages
  skips_cleanup: true
  github_token: 0bc82fda3d5d3495c28042019b5945ad7b38df14 
  keep_history: true
  on:
    branch: master
