language: node_js
node_js:
  "8.12.0"
before_install:
  npm install grunt-cli -g
install:
  npm install  
script: 
  - grunt
deploy:
  provider: pages
  skip-cleanup: true
  github-token:af4797f2b900a9012d3d1fba393b598de125c290 
  keep-history: true
  on: 
    branch: development
