language: node_js
node_js:
  "8.12.0"
before_install:
  npm install grunt-cli -g
install:
  npm install  
script: 
  - grunt
deploy:
  provider: pages
  skips_cleanup: true
  github_token: 24b5e493912508e6e79690b8828c808a10087b73
  keep_history: true
  on:
    branch: master
